version: '3'
services:
  connector-disarm-framework:
    image: opencti/connector-disarm-framework:6.2.18
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${CONNECTOR_DISARM_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_DISARM_ID}
      - "CONNECTOR_NAME=DISARM Framework"
      - CONNECTOR_SCOPE=marking-definition,identity,attack-pattern,course-of-action,intrusion-set,campaign,malware,tool,report,narrative,event,channel
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=error
      - DISARM_FRAMEWORK_URL=https://raw.githubusercontent.com/DISARMFoundation/DISARMframeworks/main/generated_files/DISARM_STIX/DISARM.json
      - DISARM_FRAMEWORK_INTERVAL=7 # In days, must be strictly greater than 1
    restart: always
    networks:
      - opencti_connector-net
    
networks:
   opencti_connector-net:
     name: opencti-docker_opencti-net
     external: true