version: '3'
services:
  connector-abuseipdb-ipblacklist:
    image: opencti/connector-abuseipdb-ipblacklist:6.2.18
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${CONNECTOR_ABUSEIPDB_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ABUSEIPDB_ID}
      - "CONNECTOR_NAME=AbuseIPDB IP Blocklist"
      - CONNECTOR_SCOPE=abuseipdb
      - CONNECTOR_LOG_LEVEL=error
      - ABUSEIPDB_URL=https://api.abuseipdb.com/api/v2/blacklist
      - ABUSEIPDB_API_KEY=${CONNECTOR_ABUSEIPDB_API_KEY}
      - ABUSEIPDB_SCORE=100
      - ABUSEIPDB_LIMIT=10000
      - ABUSEIPDB_INTERVAL=2 #Day
    restart: always
    networks:
      - opencti_connector-net
    
networks:
   opencti_connector-net:
     name: opencti-docker_opencti-net
     external: true