version: "3"
services:
  connector-vxvault:
    image: opencti/connector-vxvault:6.2.18
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${CONNECTOR_VXVAULT_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_VXVAULT_ID}
      - "CONNECTOR_NAME=VX Vault URL list"
      - CONNECTOR_SCOPE=vxvault
      - CONNECTOR_LOG_LEVEL=error
      - VXVAULT_URL=https://vxvault.net/URL_List.php
      - VXVAULT_CREATE_INDICATORS=true
      - VXVAULT_INTERVAL=3 # In days, must be strictly greater than 1
      - VXVAULT_SSL_VERIFY=False
    restart: always
    networks:
      - opencti_connector-net
    
networks:
   opencti_connector-net:
     name: opencti-docker_opencti-net
     external: true
